<a href="https://colab.research.google.com/github/Czmendoza97/IT-390/blob/main/Income_classification_models_(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**HANDS-ON SESSION-II: DATA MINING TOOLS**



**PROFESSOR: IRINA HASHMI**

**CLASSIFICATION MODELS**

IMPORT THE NECESSARY LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

IMPORT THE DATA USING PANDAS

In [14]:
NYdata=pd.read_csv('/content/sample_data/NY-House-Dataset.csv.zip')
NYdata

BROKERTITLE                TYPE  \
0           Brokered by Douglas Elliman  -111 Fifth Ave      Condo for sale   
1                                   Brokered by Serhant      Condo for sale   
2                                Brokered by Sowae Corp      House for sale   
3                                   Brokered by COMPASS      Condo for sale   
4     Brokered by Sotheby's International Realty - E...  Townhouse for sale   
...                                                 ...                 ...   
4796                                Brokered by COMPASS      Co-op for sale   
4797                    Brokered by Mjr Real Estate Llc      Co-op for sale   
4798      Brokered by Douglas Elliman - 575 Madison Ave      Co-op for sale   
4799            Brokered by E Realty International Corp      Condo for sale   
4800                 Brokered by Nyc Realty Brokers Llc      Co-op for sale   

          PRICE  BEDS       BATH  PROPERTYSQFT  \
0        315000     2   2.000000   1400.000000   
1     195000000     7  10.000000  17545.000000   
2        260000     4   2.000000   2015.000000   
3         69000     3   1.000000    445.000000   
4      55000000     7   2.373861  14175.000000   
...         ...   ...        ...           ...   
4796     599000     1   1.000000   2184.207862   
4797     245000     1   1.000000   2184.207862   
4798    1275000     1   1.000000   2184.207862   
4799     598125     2   1.000000    655.000000   
4800     349000     1   1.000000    750.000000   

                                                ADDRESS  \
0                                  2 E 55th St Unit 803   
1     Central Park Tower Penthouse-217 W 57th New Yo...   
2                                      620 Sinclair Ave   
3                               2 E 55th St Unit 908W33   
4                                           5 E 64th St   
...                                                 ...   
4796                               222 E 80th St Apt 3A   
4797                                97-40 62 Dr Unit Lg   
4798                          427 W 21st St Unit Garden   
4799                           91-23 Corona Ave Unit 4G   
4800                            460 Neptune Ave Apt 14O   

                        STATE  \
0          New York, NY 10022   
1          New York, NY 10019   
2     Staten Island, NY 10312   
3         Manhattan, NY 10022   
4          New York, NY 10065   
...                       ...   
4796      Manhattan, NY 10075   
4797      Rego Park, NY 11374   
4798       New York, NY 10011   
4799       Elmhurst, NY 11373   
4800       Brooklyn, NY 11224   

                                           MAIN_ADDRESS  \
0                2 E 55th St Unit 803New York, NY 10022   
1     Central Park Tower Penthouse-217 W 57th New Yo...   
2               620 Sinclair AveStaten Island, NY 10312   
3            2 E 55th St Unit 908W33Manhattan, NY 10022   
4                         5 E 64th StNew York, NY 10065   
...                                                 ...   
4796            222 E 80th St Apt 3AManhattan, NY 10075   
4797             97-40 62 Dr Unit LgRego Park, NY 11374   
4798        427 W 21st St Unit GardenNew York, NY 10011   
4799         91-23 Corona Ave Unit 4GElmhurst, NY 11373   
4800          460 Neptune Ave Apt 14OBrooklyn, NY 11224   

     ADMINISTRATIVE_AREA_LEVEL_2         LOCALITY      SUBLOCALITY  \
0                New York County         New York        Manhattan   
1                  United States         New York  New York County   
2                  United States         New York  Richmond County   
3                  United States         New York  New York County   
4                  United States         New York  New York County   
...                          ...              ...              ...   
4796                    New York  New York County         New York   
4797               United States         New York    Queens County   
4798               United States         New York

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [21]:
#Checking for missing data

missing=NYdata.isnull().sum()
missing



BROKERTITLE                    0
TYPE                           0
PRICE                          0
BEDS                           0
BATH                           0
PROPERTYSQFT                   0
ADDRESS                        0
STATE                          0
MAIN_ADDRESS                   0
ADMINISTRATIVE_AREA_LEVEL_2    0
LOCALITY                       0
SUBLOCALITY                    0
STREET_NAME                    0
LONG_NAME                      0
FORMATTED_ADDRESS              0
LATITUDE                       0
LONGITUDE                      0
dtype: int64

In [88]:
#Droping the not needed columns

NY_status=NYdata.drop(columns=['BROKERTITLE','LATITUDE','LONGITUDE','ADMINISTRATIVE_AREA_LEVEL_2','FORMATTED_ADDRESS','MAIN_ADDRESS'])
NY_status

TYPE      PRICE  BEDS       BATH  PROPERTYSQFT  \
0         Condo for sale     315000     2   2.000000   1400.000000   
1         Condo for sale  195000000     7  10.000000  17545.000000   
2         House for sale     260000     4   2.000000   2015.000000   
3         Condo for sale      69000     3   1.000000    445.000000   
4     Townhouse for sale   55000000     7   2.373861  14175.000000   
...                  ...        ...   ...        ...           ...   
4796      Co-op for sale     599000     1   1.000000   2184.207862   
4797      Co-op for sale     245000     1   1.000000   2184.207862   
4798      Co-op for sale    1275000     1   1.000000   2184.207862   
4799      Condo for sale     598125     2   1.000000    655.000000   
4800      Co-op for sale     349000     1   1.000000    750.000000   

                                                ADDRESS  \
0                                  2 E 55th St Unit 803   
1     Central Park Tower Penthouse-217 W 57th New Yo...   
2                                      620 Sinclair Ave   
3                               2 E 55th St Unit 908W33   
4                                           5 E 64th St   
...                                                 ...   
4796                               222 E 80th St Apt 3A   
4797                                97-40 62 Dr Unit Lg   
4798                          427 W 21st St Unit Garden   
4799                           91-23 Corona Ave Unit 4G   
4800                            460 Neptune Ave Apt 14O   

                        STATE         LOCALITY      SUBLOCALITY  \
0          New York, NY 10022         New York        Manhattan   
1          New York, NY 10019         New York  New York County   
2     Staten Island, NY 10312         New York  Richmond County   
3         Manhattan, NY 10022         New York  New York County   
4          New York, NY 10065         New York  New York County   
...                       ...              ...              ...   
4796      Manhattan, NY 10075  New York County         New York   
4797      Rego Park, NY 11374         New York    Queens County   
4798       New York, NY 10011         New York  New York County   
4799       Elmhurst, NY 11373    Queens County           Queens   
4800       Brooklyn, NY 11224     Kings County         Brooklyn   

           STREET_NAME         LONG_NAME  
0     East 55th Street   Regis Residence  
1             New York  West 57th Street  
2        Staten Island   Sinclair Avenue  
3             New York  East 55th Street  
4             New York  East 64th Street  
...                ...               ...  
4796         Manhattan               222  
4797            Queens        62nd Drive  
4798          New York  West 21st Street  
4799          Flushing             91-23  
4800      Coney Island               460  

[4801 rows x 11 columns]

In [120]:
categorical_cols = ['TYPE', 'ADDRESS', 'STATE', 'SUBLOCALITY', 'STREET_NAME', 'LONG_NAME']
numerical_cols = ['PRICE', 'BEDS', 'BATH', 'PROPERTYSQFT']

# One-hot encode categorical features
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoded_data = encoder.fit_transform(NY_status[categorical_cols])

# Create a DataFrame from encoded data
encoded_columns = encoder.get_feature_names_out(categorical_cols)
df_encoded = pd.DataFrame(encoded_data, columns=encoded_columns, index=NY_status.index)

# Combine numerical data and encoded categorical data
X = pd.concat([NY_status[numerical_cols], df_encoded], axis=1)
y = NY_status['LOCALITY']
df_encoded

TYPE_Coming Soon  TYPE_Condo for sale  TYPE_Condop for sale  \
0                  0.0                  1.0                   0.0   
1                  0.0                  1.0                   0.0   
2                  0.0                  0.0                   0.0   
3                  0.0                  1.0                   0.0   
4                  0.0                  0.0                   0.0   
...                ...                  ...                   ...   
4796               0.0                  0.0                   0.0   
4797               0.0                  0.0                   0.0   
4798               0.0                  0.0                   0.0   
4799               0.0                  1.0                   0.0   
4800               0.0                  0.0                   0.0   

      TYPE_Contingent  TYPE_For sale  TYPE_Foreclosure  TYPE_House for sale  \
0                 0.0            0.0               0.0                  0.0   
1                 0.0            0.0               0.0                  0.0   
2                 0.0            0.0               0.0                  1.0   
3                 0.0            0.0               0.0                  0.0   
4                 0.0            0.0               0.0                  0.0   
...               ...            ...               ...                  ...   
4796              0.0            0.0               0.0                  0.0   
4797              0.0            0.0               0.0                  0.0   
4798              0.0            0.0               0.0                  0.0   
4799              0.0            0.0               0.0                  0.0   
4800              0.0            0.0               0.0                  0.0   

      TYPE_Land for sale  TYPE_Mobile house for sale  \
0                    0.0                         0.0   
1                    0.0                         0.0   
2                    0.0                         0.0   
3                    0.0                         0.0   
4                    0.0                         0.0   
...                  ...                         ...   
4796                 0.0                         0.0   
4797                 0.0                         0.0   
4798                 0.0                         0.0   
4799                 0.0                         0.0   
4800                 0.0                         0.0   

      TYPE_Multi-family home for sale  ...  LONG_NAME_Woodrow Road  \
0                                 0.0  ...                     0.0   
1                                 0.0  ...                     0.0   
2                                 0.0  ...                     0.0   
3                                 0.0  ...                     0.0   
4                                 0.0  ...                     0.0   
...                               ...  ...                     ...   
4796                              0.0  ...                     0.0   
4797                              0.0  ...                     0.0   
4798                              0.0  ...                     0.0   
4799                              0.0  ...                     0.0   
4800                              0.0  ...                     0.0   

      LONG_NAME_Wooster Street  LONG_NAME_Wright Street  \
0                          0.0                      0.0   
1                          0.0                      0.0   
2                          0.0                      0.0   
3                          0.0                      0.0   
4                          0.0                      0.0   
...                        ...                      ...   
4796                       0.0                      0.0   
4797                       0.0                      0.0   
4798                       0.0                      0.0   
4799                       0.0                      0.0   
4800                       0.0                      0.0   

     

In [121]:
#spliting into sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [122]:
# Initialize the Logistic Regression model
logistic_model = LogisticRegression(max_iter=100, random_state=42)

# Fit the model on the training data
logistic_model.fit(X_train, y_train)
# Predict on the testing set
y_pred = logistic_model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [123]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
# Display a classification report for precision, recall, and F1-score
print("Classification Report:\n", classification_report(y_test, y_pred))

# Display a confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.51
Classification Report:
                  precision    recall  f1-score   support

   Bronx County       0.00      0.00      0.00        41
       Brooklyn       0.00      0.00      0.00         2
   Kings County       0.00      0.00      0.00        98
       New York       0.51      1.00      0.68       492
New York County       0.00      0.00      0.00       194
  Queens County       0.00      0.00      0.00       117
Richmond County       0.00      0.00      0.00         9
      The Bronx       0.00      0.00      0.00         1
  United States       0.00      0.00      0.00         7

       accuracy                           0.51       961
      macro avg       0.06      0.11      0.08       961
   weighted avg       0.26      0.51      0.35       961

Confusion Matrix:
 [[  0   0   0  41   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0]
 [  0   0   0  98   0   0   0   0   0]
 [  0   0   0 492   0   0   0   0   0]
 [  0   0   0 194   0   0   0   0   0]
 [ 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [124]:

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Display a classification report for precision, recall, and F1-score
print("Classification Report:\n", classification_report(y_test, y_pred))

# Display a confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.51
Classification Report:
                  precision    recall  f1-score   support

   Bronx County       0.00      0.00      0.00        41
       Brooklyn       0.00      0.00      0.00         2
   Kings County       0.00      0.00      0.00        98
       New York       0.51      1.00      0.68       492
New York County       0.00      0.00      0.00       194
  Queens County       0.00      0.00      0.00       117
Richmond County       0.00      0.00      0.00         9
      The Bronx       0.00      0.00      0.00         1
  United States       0.00      0.00      0.00         7

       accuracy                           0.51       961
      macro avg       0.06      0.11      0.08       961
   weighted avg       0.26      0.51      0.35       961

Confusion Matrix:
 [[  0   0   0  41   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0]
 [  0   0   0  98   0   0   0   0   0]
 [  0   0   0 492   0   0   0   0   0]
 [  0   0   0 194   0   0   0   0   0]
 [ 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
